# Generated by Django 2.2.10 on 2020-02-11 02:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='users',
            field=models.ManyToManyField(related_name='stores', to=settings.AUTH_USER_MODEL),
        ),
    ]
