# Generated by Django 2.2.10 on 2020-02-13 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'permissions': (('manage_stores', 'Manage stores'),)},
        ),
    ]
