# Generated by Django 2.2.10 on 2020-02-11 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_users'),
        ('account', '0038_auto_20200123_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.Store'),
        ),
    ]
